### PR TITLE
Minor fix for huge member tables

### PR DESCRIPTION
**Pull request by spekulatius**
My solution is to limit the users list to the users with access to the workflows dashboard.

@nyeholt are you happy with this?

### CODE REVIEW

**Comment by nyeholt** [comment]
I don't like the implied requirement of having the Dashboards module installed. WorkflowDefinition does

`$cmsUsers = Member::mapInCMSGroups();`

which, while not perfect, does trim the user set down quite a lot. Could you swap it to that?

**Comment by spekulatius** [comment]
Thanks for your reply Marcus. Sure, makes sense. I have changed this.

**Comment by spekulatius** [comment]
Do you want to merge this @nyeholt ?

**Comment by nyeholt** [comment]
Oops, missed the previous update :)

**Comment by spekulatius** [comment]
no problem

**Pull request merged**
