### PR TITLE
META: Add action to build docs on Netlify

### PR DESCRIPTION
**Pull request by unclecheese**

### CODE REVIEW

**Comment by unclecheese** [comment]
Please write to aaron at ss.com to obtain the dependent secret.

**Comment by emteknetnz** [comment]
@unclecheese Is this ready to be merged as is?

**Comment by unclecheese** [comment]
No, per the above comment, I need an administrator to add the secret. That's the major bottleneck with these PRs.

**Comment by emteknetnz** [comment]
Related PRs:
https://github.com/symbiote/silverstripe-advancedworkflow/pull/413
https://github.com/symbiote/silverstripe-advancedworkflow/pull/414

**Comment by emteknetnz** [comment]
@unclecheese OK I'll follow this up for you

**Comment by brynwhyman** [comment]
Hey @nglasl is this something you can please help with? This is currently blocking the docs for this module appearing in the new Netlify-based Silverstripe docs site.

Perhaps pinging @unclecheese under the same alias on the Silverstripe Community Slack workspace could be a good next step to getting the secret?

**Review by nglasl — APPROVED** [review]

**Comment by nglasl** [comment]
Apologies for the delay here, I've been away on leave for the past couple of weeks. This should now be sorted.

**Pull request merged**
