### PR TITLE
added extra hook so you can mess with the readonly form

### PR DESCRIPTION
**Pull request by pitchandtone**
I've added a cancel button and because you can't technically edit the model at this point you need to mark that specific action as not readonly.

### CODE REVIEW

**Comment by pitchandtone** [comment]
Updated to be outside the if.

**Comment by pitchandtone** [comment]
Travis fail seems unrelated.

**Comment by tractorcow** [comment]
Yep, it's 4.x being incompatible.

**Comment by tractorcow** [comment]
> Would it be better to instead have a general "updateWorkflowEditForm"

Since your extension hook is specific to workflow module, wouldn't this be a better name for the extension hook? It's too similar (as it stands) to updateEditForm.

**Comment by pitchandtone** [comment]
Done @tractorcow

**Comment by pitchandtone** [comment]
@nyeholt are you OK to merge this?

**Pull request merged**
