### PR TITLE
Added QueuedJobs dependency

### PR DESCRIPTION
**Pull request by assertchris**
Context: https://github.com/silverstripe-australia/advancedworkflow/blob/689f7bf5f8d8255f099d7295f5c59405bc67e223/code/extensions/WorkflowEmbargoExpiryExtension.php#L18-L21

### CODE REVIEW

**Comment by assertchris** [comment]
My head hurts trying to work out this dependency graph. It's not currently causing exceptions because `advancedworkflow` and `queuedjobs` are listed as dependencies in `cwp-recipe-basic`. If `advancedworkflow` is used outside of `cwp-recipe-basic` (and without `queuedjobs`) then `/dev/build` screams...

**Comment by nyeholt** [comment]
Odd that this has never come up before - in fact there's a couple of other bits of functionality that explicitly check for the existence of queuedjobs before defining, I wonder why this never complained previously. 

Anyway - can you change the version dependency to something less restrictive? Preferably ~2.6 as that'll fix it to the backwards compatible line - projects can define a more specific locking if they want.

**Comment by assertchris** [comment]
We've not fully tested the "supported" modules with 3.2, so there may be more compelling reasons to change the dependency version to something else. It depends on which modules support 3.2 (via `composer.json`) and which don't. 
 
The reason it's not come up before is because `3.2` uses a new ORM, and the new ORM checks to see if the class hierarchy includes a valid `DataObject` subclass. Without `queuedjobs`, there is no valid `DataObject` in the hierarchy...

Leaving this alone for now, until we've tested `3.2` more...

**Comment by nyeholt** [comment]
Ah that makes sense then :)

**Pull request closed without merging**
