### PR TITLE
DEP Upgrade frontend build stack

### PR DESCRIPTION
**Pull request by GuySartorelli**
See https://github.com/silverstripe/silverstripe-admin/pull/1389 for a wider discussion on most of the changes

## Parent issue
- https://github.com/silverstripeltd/product-issues/issues/644

### CODE REVIEW

**Review by emteknetnz — CHANGES_REQUESTED** [review]
Tried testing, though there's a PHP error in there when I edit a workflow in the Workflows ModelAdmin

Invalid sort column "Member"."Surname"
DataList->validateSortColumn():374

It's related to making DataList->sort() no longer accepting raw sql, somewhere in the code you'll need to change a ->sort($sort) to an ->orderBy($sort)

**Comment by GuySartorelli** [comment]
Oops, yup this is something that I had fixed locally at the time but forgot to create a PR. The problem is actually in framework.
See https://github.com/silverstripe/silverstripe-framework/pull/10675

**Review by emteknetnz — CHANGES_REQUESTED** [review]
I tried adding a new workflow step on the default workflow and I got this error

image

**Comment by GuySartorelli** [comment]
Admin needed the jquery ui fix to be merged up. I thought I had tested this one but I guess not... gave it a good run through its paces this time and seems fine. You'll want to pull the latest `2` from admin to get the merged up jqueryui changes.

Note there is a new related issue: https://github.com/symbiote/silverstripe-advancedworkflow/issues/480

**Review by emteknetnz — APPROVED** [review]

**Pull request merged**
