### PR TITLE
changing classname due to some weird logic or old code

### PR DESCRIPTION
**Pull request by pitchandtone**
I happen to have a ListingPage class (not associated with the module) but not a ListingTemplate, so code breaks.

### CODE REVIEW

**Comment by pitchandtone** [comment]
Sorry rather than fixing the bug you want me to remove the code altogether?

Shall I just add an ->extend call so that someone can move the whole ListingTemplate stuff to that?

It's weird because the db array has a ListingTemplateID in it too.

**Comment by tractorcow** [comment]
It looks like this module https://github.com/nyeholt/silverstripe-listingpage

It was introduced in this commit https://github.com/dnadesign/advancedworkflow/commit/6d09941d2c65a9a9430ac7784f46c54651341715

@nyeholt shouldn't all of this really be in an extension with an updateCMSFields hook? You could conditionally add this extension via `moduleexists` condition in yml like how fulltextsearch does https://github.com/silverstripe-labs/silverstripe-fulltextsearch/blob/master/_config/processor.yml

I would say to, as @pitchandtone  suggested, remove the code altogether.

**Comment by pitchandtone** [comment]
Better?

**Comment by tractorcow** [comment]
It looks good to me....

Ignore the 4.0 errors since the whole API is incompatible with anything 3.x now.

@phptek do you want to comment an the module decoupling from listingpage?

**Comment by nyeholt** [comment]
Yes agreed to remove it, I believe it was originally introduced during 2.4 prior to any nice config stuff at the specific request of someone - would be best purged and managed as a separate extension.

**Pull request merged**
