### PR TITLE
Fix embargo publishDate selector

### PR DESCRIPTION
**Pull request by brettt89**
Replace #PublishOnDate selector with #Form_EditForm_PublishOnDate_Holder
File: javascript/WorkFlowField.js

### CODE REVIEW

**Comment by tractorcow** [comment]
Won't work in 3.1 though. :)

**Comment by tractorcow** [comment]
Try using a selector based on name= property instead of ID

**Comment by brettt89** [comment]
Updated selector to use "'nput[name="PublishOnDate[date]"]' rather than ID

**Comment by tractorcow** [comment]
Tests died... restarting.

Ping me if you need them restarted again. :D

**Pull request merged**
