### PR TITLE
Fixes for #202

### PR DESCRIPTION
**Pull request by nyeholt**
Provides some fixes for #202 - there's still a couple of UI issues, but the functionality actually proceeds.

### CODE REVIEW

**Comment by phptek** [comment]
@nyeholt Looks good AFAIKT, just keen not to let UI issue slide-by unless they are a). addressed or b). Can be ref'd in an issue somewhere so they're easily identified and can be picked-up by a dev at a later date.

**Comment by nyeholt** [comment]
Yeah I'm not either, however the issue is in functionality that wasn't previously available at all (workflow in model admin). The hope is to make it available in dev-master now for people to look at and try using, and possibly fixing, before stabilising it for an actual release tag. It's currently referenced from #202, but I'll create a more descriptive issue about the exact display issues.

**Comment by nyeholt** [comment]
Actually, will hold off on merging this until a bit later today, I should have some time to try and nut out the problem.

**Comment by phptek** [comment]
Nice one :-)

**Comment by nyeholt** [comment]
Turns out it was pretty straightforward to resolve. Will merge to master now, will move across to the stable branch later this week.

**Pull request merged**
